language: php


script:
  - ./bin/phpunit --coverage-clover=build/logs/clover.xml

matrix:
  include:
   - php: 7.1
     env: PHPUNIT_VERSION=6.5.14
     dist: trusty

   - php: 7.1
     env: PHPUNIT_VERSION=7.5
     dist: trusty

   - php: 7.2
     env: PHPUNIT_VERSION=6.5.14
     dist: trusty

   - php: 7.2
     env: PHPUNIT_VERSION=7.5
     dist: trusty

   - php: 7.2
     env: PHPUNIT_VERSION=8.1
     dist: trusty

   - php: 7.3
     env: PHPUNIT_VERSION=7.5
     dist: trusty

   - php: 7.3
     env: PHPUNIT_VERSION=8.1
     dist: trusty

   - php: 7.3
     env: PHPUNIT_VERSION=9.0
     dist: trusty

   - php: 7.3
     env: PHPUNIT_VERSION=9.5
     dist: xenial

   - php: 7.4
     env: PHPUNIT_VERSION=8.5
     dist: xenial

   - php: 7.4
     env: PHPUNIT_VERSION=9.0
     dist: xenial

   - php: 7.4
     env: PHPUNIT_VERSION=9.5
     dist: xenial

   - php: 8.0
     env: PHPUNIT_VERSION=8.5
     dist: xenial

   - php: 8.0
     env: PHPUNIT_VERSION=9.5
     dist: xenial

install:
  - composer require --dev --ignore-platform-reqs phpunit/phpunit:${PHPUNIT_VERSION} 
  - composer install --dev --ignore-platform-reqs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - CODECLIMATE_REPO_TOKEN=74f9cd376c20c19d09d6c73e4bac9dad48209fa7f3fb44b650ec7d70db81a51a ./bin/test-reporter
